#### import csv 
# Write a csv file based on Covid-19 Cases in the World -- dee
def main():
    write_data()

# Data is based on: https://covid19.who.int/table by the World Health Organization as of June 12, 2021 (4:53pm, Philippine Standard Time)
# Data includes the name of the country, region of the country, total number of cases, new cases, and cummulative deaths per country
def write_data():
    with open("data.csv", "w") as f:
        columns = ['country', 'code', 'year', 'digital', 'deaths', 'transmission classification']
        writer = csv.DictWriter(f, fieldnames=columns)
        writer.writeheader()
        writer.writerow({'country': 'Afghanistan','region': 'Eastern Mediterranean','total': 85892,'new': 1842,'deaths': 3356,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Albania','region': 'Europe','total': 132415,'new': 18,'deaths': 2452,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Algeria','region': 'Africa','total': 1132034,'new': 387,'deaths': 3544,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'American Samoa','region': 'Western Pacific','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Andorra','region': 'Europe','total': 1,'new': 10,'deaths': 0,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Angola','region': 'Africa','total': 13791,'new': 151,'deaths': 127,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Anguilla','region': 'Americas','total': 109,'new': 0,'deaths': 0,'transmission classification': 'Clusters of Cases'})
        writer.writerow({'country': 'Antigua and Barbuda','region': 'Americas','total': 1263,'new': 0,'deaths': 42,'transmission classification': 'Clusters of Cases'})
        writer.writerow({'country': 'Argentina','region': 'Americas','total': 4008771,'new': 31137,'deaths': 82667,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Armenia','region': 'Europe','total': 223460,'new': 76,'deaths': 4478,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Aruba','region': 'Americas','total': 11604,'new': 5,'deaths': 107,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Australia','region': 'Western Pacific','total': 30210,'new': 6,'deaths': 910,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Austria','region': 'Europe','total': 643651,'new': 328,'deaths': 10388,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Azerbaijan','region': 'Europe','total': 334917,'new': 68,'deaths': 4948,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Bahamas','region': 'Americas','total': 12027,'new': 0,'deaths': 232,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Bahrain','region': 'Eastern Mediterranean','total': 254920,'new': 1041,'deaths': 1171,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Bangladesh','region': 'South-East Asia','total': 817819,'new': 2537,'deaths': 12949,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Barbados','region': 'Americas','total': 4032,'new': 0,'deaths': 47,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Belarus','region': 'Europe','total': 402853,'new': 834,'deaths': 2939,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Belgium','region': 'Europe','total': 1073358,'new': 3,'deaths': 25061,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Belize','region': 'Americas','total': 12109,'new': 10,'deaths': 325,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Benin','region': 'Africa','total': 8109,'new': 27,'deaths': 102,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Bermuda','region': 'Americas','total': 2497,'new': 0,'deaths': 33,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Bhutan','region': 'South-East Asia','total': 1739,'new': 15,'deaths': 1,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Bolivia','region': 'Americas','total': 392975,'new': 2981,'deaths': 15177,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Bonaire','region': 'Americas','total': 1590,'new': 0,'deaths': 17,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Bosnia and Herzegovina','region': 'Europe','total': 204512,'new': 57,'deaths': 9467,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Botswana','region': 'Africa','total': 60648,'new': 0,'deaths': 885,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Brazil','region': 'Americas','total': 17037129,'new': 52911,'deaths': 2378,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'British Virgin Islands','region': 'Americas','total': 290,'new': 0,'deaths': 1,'transmission classification': 'Clusters of Cases'})
        writer.writerow({'country': 'Brunei','region': 'Western Pacific','total': 246,'new': 0,'deaths': 3,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Bulgaria','region': 'Europe','total': 419990,'new': 131,'deaths': 17872,'transmission classification': 'Clusters of Cases'})
        writer.writerow({'country': 'Burkina Faso','region': 'Africa','total': 13454,'new': 0,'deaths': 167,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Burundi','region': 'Africa','total': 4960,'new': 18,'deaths': 8,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Cabo Verde','region': 'Africa','total': 31339,'new': 114,'deaths': 270,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Cambodia','region': 'Western Pacific','total': 36240,'new': 729,'deaths': 289,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Cameroon','region': 'Africa','total': 79904,'new': 0,'deaths': 1302,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Canada','region': 'Americas','total': 1395410,'new': 1265,'deaths': 25791,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Cayman Islands','region': 'Americas','total': 592,'new': 1,'deaths': 2,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Central African Republic','region': 'Africa','total': 7101,'new': 0,'deaths': 98,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Chad','region': 'Africa','total': 4942,'new': 0,'deaths': 174,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Chile','region': 'Americas','total': 1445770,'new': 5353,'deaths': 30141,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'China','region': 'Western Pacific','total': 115229,'new': 301,'deaths': 5179,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Colombia','region': 'Americas','total': 3611602,'new': 18586,'deaths': 92923,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Comoros','region': 'Africa','total': 3961,'new': 1,'deaths': 146,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Congo','region': 'Africa','total': 11920,'new': 0,'deaths': 155,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Cook Islands','region': 'Western Pacific','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Costa Rica','region': 'Americas','total': 33820,'new': 1900,'deaths': 4251,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Croatia','region': 'Europe','total': 358061,'new': 0,'deaths': 8103,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Cuba','region': 'Americas','total': 152420,'new': 1161,'deaths': 1045,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Curacao','region': 'Americas','total': 12281,'new': 1,'deaths': 123,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Cyprus','region': 'Europe','total': 72996,'new': 77,'deaths': 367,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Czechia','region': 'Europe','total': 1664649,'new': 267,'deaths': 30211,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': "Cote d'lvoire",'region': 'Africa','total': 47547,'new': 36,'deaths': 306,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Denmark','region': 'Europe','total': 288229,'new': 904,'deaths': 2520,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Democratic Republic of Congo','region': 'Africa','total': 34226,'new': 310,'deaths': 825,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Djibouti','region': 'Eastern Mediterranean','total': 11567,'new': 1,'deaths': 154,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Dominica','region': 'Americas','total': 188,'new': 0,'deaths': 0,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Dominican Republic','region': 'Americas','total': 304428,'new': 1440,'deaths': 3686,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Ecuador','region': 'Americas','total': 433870,'new': 885,'deaths': 20903,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Egypt','region': 'Eastern Mediterranean','total': 270292,'new': 765,'deaths': 15471,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'El Salvador','region': 'Americas','total': 74983,'new': 842,'deaths': 2279,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Equatorial Guinea','region': 'Africa','total': 8640,'new': 0,'deaths': 118,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Eritrea','region': 'Africa','total': 4690,'new': 93,'deaths': 14,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Estonia','region': 'Europe','total': 130364,'new': 54,'deaths': 1266,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Eswatini','region': 'Africa','total': 18694,'new': 14,'deaths': 676,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Ethiopia','region': 'Africa','total': 273398,'new': 223,'deaths': 4226,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Falkland Islands','region': 'Americas','total': 63,'new': 0,'deaths': 0,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Faroe Islands','region': 'Europe','total': 752,'new': 5,'deaths': 1,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Fiji','region': 'Western Pacific','total': 880,'new': 35,'deaths': 4,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Finland','region': 'Europe','total': 93520,'new': 126,'deaths': 964,'transmission classification': 'Clusters of Cases'})
        writer.writerow({'country': 'France','region': 'Europe','total': 5621275,'new': 5358,'deaths': 109336,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'French Guinea','region': 'Americas','total': 25292,'new': 199,'deaths': 130,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'French Polynesia','region': 'Western Pacific','total': 18914,'new': 12,'deaths': 142,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Gabon','region': 'Africa','total': 24696,'new': 45,'deaths': 156,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Gambia','region': 'Africa','total': 6008,'new': 6,'deaths': 180,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Georgia','region': 'Europe','total': 351954,'new': 705,'deaths': 4996,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Germany','region': 'Europe','total': 3709129,'new': 3187,'deaths': 89585,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Ghana','region': 'Africa','total': 94369,'new': 141,'deaths': 789,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Gibraltar','region': 'Europe','total': 4302,'new': 2,'deaths': 94,'transmission classification': 'Clusters of Cases'})
        writer.writerow({'country': 'Greece','region': 'Europe','total': 412420,'new': 886,'deaths': 12346,'transmission classification': 'Clusters of Cases'})
        writer.writerow({'country': 'Greenland','region': 'Europe','total': 43,'new': 0,'deaths': 0,'transmission classification': 'No Active Cases'})
        writer.writerow({'country': 'Grenada','region': 'Americas','total': 161,'new': 0,'deaths': 1,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Guadeloupe','region': 'Americas','total': 17108,'new': 0,'deaths': 260,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Guam','region': 'Western Pacific','total': 7973,'new': 6,'deaths': 139,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Guatemala','region': 'Americas','total': 263836,'new': 0,'deaths': 8331,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Guernsey','region': 'Europe','total': 823,'new': 0,'deaths': 17,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Guinea','region': 'Africa','total': 23334,'new': 22,'deaths': 165,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Guinea-Bissau','region': 'Africa','total': 3794,'new': 4,'deaths': 68,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Guyana','region': 'Americas','total': 17805,'new': 87,'deaths': 416,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Haiti','region': 'Americas','total': 16001,'new': 0,'deaths': 342,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Holy See','region': 'Europe','total': 26,'new': 0,'deaths': 0,'transmission classification': 'No Active Cases'})
        writer.writerow({'country': 'Honduras','region': 'Americas','total': 242796,'new': 419,'deaths': 6532,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Hungary','region': 'Europe','total': 806385,'new': 0,'deaths': 29805,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Iceland','region': 'Europe','total': 6616,'new': 4,'deaths': 30,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'India','region': 'South-East Asia','total': 29183121,'new': 94052,'deaths': 359676,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Indonesia','region': 'South-East Asia','total': 1877050,'new': 7725,'deaths': 52162,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Iran','region': 'Eastern Mediterranean','total': 2990714,'new': 10598,'deaths': 81519,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Iraq','region': 'Eastern Mediterranean','total': 1237856,'new': 4616,'deaths': 16614,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Ireland','region': 'Europe','total': 264909,'new': 0,'deaths': 4941,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Isle of Man','region': 'Europe','total': 1598,'new': 0,'deaths': 29,'transmission classification': 'No Active Cases'})
        writer.writerow({'country': 'Israel','region': 'Europe','total': 839624,'new': 39,'deaths': 6428,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Italy','region': 'Europe','total': 4237790,'new': 2198,'deaths': 126767,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Jamaica','region': 'Americas','total': 49090,'new': 59,'deaths': 988,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Japan','region': 'Western Pacific','total': 767808,'new': 2189,'deaths': 13841,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Jersey','region': 'Europe','total': 3257,'new': 4,'deaths': 69,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Jordan','total': 741699,'new': 598,'deaths': 9561,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Kazakhstan','region': 'Europe','total': 453975,'new': 0,'deaths': 7465,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Kenya','region': 'Africa','total': 173661,'new': 589,'deaths': 3345,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Kiribati','region': 'Western Pacific','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Kosovo','total': 107490,'new': 21,'deaths': 2237,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Kuwait','region': 'Eastern Mediterranean','total': 321648,'new': 1391,'deaths': 1806,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Kyrgyztan','region': 'Europe','total': 108667,'new': 494,'deaths': 1869,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': "Lao People's Democratic Republic",'region': 'Western Pacific','total': 1971,'new': 1,'deaths': 3,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Latvia','region': 'Europe','total': 135388,'new': 244,'deaths': 2428,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Lebanon','region': 'Eastern Mediterranean','total': 541940,'new': 139,'deaths': 7780,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Lesotho','region': 'Africa','total': 10839,'new': 0,'deaths': 326,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Liberia','region': 'Africa','total': 2382,'new': 92,'deaths': 88,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Libya','region': 'Eastern Mediterranean','total': 188157,'new': 229,'deaths': 3152,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Liechtenstein','region': 'Europe','total': 3114,'new': 0,'deaths': 57,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Lithuania','region': 'Europe','total': 277222,'new': 220,'deaths': 4327,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Luxembourg','region': 'Europe','total': 70343,'new': 52,'deaths': 818,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Madagascar','region': 'Africa','total': 41786,'new': 28,'deaths': 874,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Malawi','region': 'Africa','total': 34432,'new': 22,'deaths': 1158,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Malaysia','region': 'Western Pacific','total': 633891,'new': 6239,'deaths': 3611,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Maldives','region': 'South-East Asia','total': 69213,'new': 341,'deaths': 191,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Mali','region': 'Africa','total': 14328,'new': 4,'deaths': 521,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Malta','region': 'Europe','total': 30573,'new': 1,'deaths': 419,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Marshall Islands','region': 'Western Pacific','total': 4,'new': 0,'deaths': 0,'transmission classification': 'No Active Cases'})
        writer.writerow({'country': 'Martinique','region': 'Americas','total': 12060,'new': 0,'deaths': 97,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Mauritania','region': 'Africa','total': 19923,'new': 28,'deaths': 470,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Mauritius','region': 'Africa','total': 1519,'new': 0,'deaths': 18,'transmission classification': 'Clusters of Cases'})
        writer.writerow({'country': 'Mayotte','region': 'Africa','total': 19355,'new': 0,'deaths': 173,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Mexico','region': 'Americas','total': 2438011,'new': 3449,'deaths': 229100,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Micronesia','region': 'Western Pacific','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Monaco','region': 'Europe','total': 2514,'new': 3,'deaths': 33,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Mongolia','region': 'Western Pacific','total': 69022,'new': 1312,'deaths': 324,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Montenegro','region': 'Europe','total': 99858,'new': 0,'deaths': 1596,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Montserrat','region': 'Americas','total': 20,'new': 0,'deaths': 1,'transmission classification': 'No Active Cases'})
        writer.writerow({'country': 'Morroco','region': 'Eastern Mediterranean','total': 522765,'new': 376,'deaths': 9192,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Mozambique','region': 'Africa','total': 71239,'new': 74,'deaths': 840,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Myanmar','region': 'South-East Asia','total': 144715,'new': 136,'deaths': 3233,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Namibia','region': 'Africa','total': 60329,'new': 515,'deaths': 950,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Nauru','region': 'Western Pacific','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Nepal','region': 'South-East Asia','total': 598813,'new': 3449,'deaths': 8179,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Netherlands','region': 'Europe','total': 1667560,'new': 1791,'deaths': 17700,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'New Caledonia','region': 'Western Pacific','total': 128,'new': 0,'deaths': 0,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'New Zealand','region': 'Western Pacific','total': 2341,'new': 1,'deaths': 26,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Nicaragua','region': 'Americas','total': 6085,'new': 0,'deaths': 188,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Niger','region': 'Africa','total': 5442,'new': 3,'deaths': 192,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Nigeria','region': 'Africa','total': 166982,'new': 64,'deaths': 2117,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Niue','region': 'Western Pacific','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Norfolk island','region': 'Western Pacific','total': 183,'new': 0,'deaths': 2,'transmission classification': 'No Active Cases'})
        writer.writerow({'country': 'North Macedonia','region': 'Europe','total': 155469,'new': 28,'deaths': 5467,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Northern Mariana Islands','region': 'Western Pacific','total': 183,'new': 0,'deaths': 2,'transmission classification': 'Pending'})
        writer.writerow({'country': 'Norway','region': 'Europe','total': 127254,'new': 191,'deaths': 789,'transmission classification': 'Clusters of Cases'})
        writer.writerow({'country': 'Oman','region': 'Eastern Mediterranean','total': 228579,'new': 1895,'deaths': 2448,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Pakistan','region': 'Eastern Mediterranean','total': 936131,'new': 1118,'deaths': 21453,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Palau','region': 'Western Pacific','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Palestenian Territory','region': 'Eastern Mediterranean','total': 339631,'new': 246,'deaths': 3790,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Panama','region': 'Americas','total': 383733,'new': 882,'deaths': 6408,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Papua New Guinea','region': 'Western Pacific','total': 16580,'new': 0,'deaths': 164,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Paraguay','region': 'Americas','total': 379131,'new': 3135,'deaths': 10145,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Peru','region': 'Americas','total': 1987933,'new': 2934,'deaths': 187157,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Philippines','region': 'Western Pacific','total': 1293687,'new': 7485,'deaths': 22312,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Pitcairn Islands','region': 'Western Pacific','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Poland','region': 'Europe','total': 2876667,'new': 378,'deaths': 74447,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Portugal','region': 'Europe','total': 854522,'new': 890,'deaths': 17307,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Puerto Rico','region': 'Americas','total': 139142,'new': 10,'deaths': 2524,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Qatar','region': 'Eastern Mediterranean','total': 219138,'new': 158,'deaths': 573,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Republic of Korea','region': 'Western Pacific','total': 146303,'new': 611,'deaths': 1979,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Republic of Moldova','region': 'Europe','total': 255601,'new': 60,'deaths': 6145,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Romania','region': 'Europe','total': 1079294,'new': 140,'deaths': 31383,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Russian Federation','region': 'Europe','total': 5167949,'new': 11699,'deaths': 125278,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Rwanda','region': 'Africa','total': 27434,'new': 127,'deaths': 364, 'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Reunion','region': 'Africa','total': 27235,'new': 0,'deaths': 212, 'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Saba','region': 'Americas','total': 7,'new': 0,'deaths': 0,'transmission classification': 'No Active Cases'})
        writer.writerow({'country': 'Saint Barthelemy','region': 'Americas','total': 1029,'new': 0,'deaths': 1,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Saint Helena','region': 'Africa','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Saint Kitts and Nevis','region': 'Americas','total': 119,'new': 25,'deaths': 0,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Saint Lucia','region': 'Americas','total': 5148,'new': 10,'deaths': 80,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Saint Martin','region': 'Americas','total': 2113,'new': 0,'deaths': 22,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Saint Pierre and Miguelon','region': 'Americas','total': 25,'new': 0,'deaths': 0,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Saint Vincent and the Grenadines','region': 'Americas','total': 2092,'new': 7,'deaths': 12,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Samoa','region': 'Western Pacific','total': 1,'new': 0,'deaths': 0,'transmission classification': 'No Active Cases'})
        writer.writerow({'country': 'San Marino','region': 'Europe','total': 5090,'new': 0,'deaths': 90,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'San Tome and Principe','region': 'Africa','total': 2354,'new': 1,'deaths': 37,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Saudi Arabia','region': 'Eastern Mediterranean','total': 461242,'new': 1274,'deaths': 7503,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Senegal','region': 'Africa','total': 41796,'new': 71,'deaths': 1150,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Serbia','region': 'Europe','total': 714252,'new': 198,'deaths': 6938,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Seychelles','region': 'Africa','total': 12813,'new': 202,'deaths': 42,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Sierra Leone','region': 'Africa','total': 4251,'new': 43,'deaths': 82,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Singapore','region': 'Western Pacific','total': 62223,'new': 4,'deaths': 34,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Sint Eustatius','region': 'Americas','total': 20,'new': 0,'deaths': 0,'transmission classification': 'No Active Cases'})
        writer.writerow({'country': 'Sint Maartin','region': 'Americas','total': 2495,'new': 11,'deaths': 30,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Slovakia','region': 'Europe','total': 390809,'new': 116,'deaths': 12433,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Slovenia','region': 'Europe','total': 255908,'new': 255,'deaths': 4709,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Solomon Islands','region': 'Western Pacific','total': 20,'new': 0,'deaths': 0,'transmission classification': 'No Active Cases'})
        writer.writerow({'country': 'Somalia','region': 'Eastern Mediterranean','total': 14779,'new': 3,'deaths': 774,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'South Africa','region': 'Africa','total': 1712939,'new': 8881,'deaths': 57310,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'South Sudan','region': 'Africa','total': 10688,'new': 0,'deaths': 115,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Spain','region': 'Europe','total': 3715454,'new': 2162,'deaths': 80332,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Sri Lanka','region': 'South-East Asia','total': 213396,'new': 2735,'deaths': 1910,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Sudan','region': 'Eastern Mediterranean','total': 36203,'new': 0,'deaths': 2719,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Suriname','region': 'Americas','total': 17041,'new': 255,'deaths': 363,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Sweden','region': 'Europe','total': 1081898,'new': 1175,'deaths': 14562,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Switzerland','region': 'Europe','total': 696225,'new': 1,'deaths': 10238,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Syrian Arab Republic','region': 'Eastern Mediterranean','total': 24723,'new': 33,'deaths': 1801,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Tajikistan','region': 'Europe','total': 13714,'new': 0,'deaths': 91,'transmission classification': 'Pending'})
        writer.writerow({'country': 'Thailand','region': 'South-East Asia','total': 187538,'new': 2310,'deaths': 1375,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Timor-Leste','region': 'South-East Asia','total': 8113,'new': 172,'deaths': 18,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Togo','region': 'Africa','total': 13563,'new': 12,'deaths': 126,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Tokelau','region': 'Western Pacific','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Tonga','region': 'Western Pacific','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Trinidad and Tobago','region': 'Americas','total': 27079,'new': 280,'deaths': 599,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Tunisia','region': 'Eastern Mediterranean','total': 360285,'new': 2102,'deaths': 13229,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Turkey','region': 'Europe','total': 5306690,'new': 6454,'deaths': 48428,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Turkmenistan','region': 'Europe','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Turks and Caicos Islands','region': 'Americas','total': 2421,'new': 0,'deaths': 18,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Tuvalu','region': 'Western Pacific','total': 0,'new': 0,'deaths': 0,'transmission classification': 'No Cases'})
        writer.writerow({'country': 'Uganda','region': 'Africa','region': 'Africa','total': 55551,'new': 842,'deaths': 402,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Ukraine','region': 'Europe','total': 2219824,'new': 1785,'deaths': 51507,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'United Arab Emirates','region': 'Eastern Mediterranean','total': 589423,'new': 2179,'deaths': 1710,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'United Kingdom','region': 'Europe','total': 4535758,'new': 7312,'deaths': 127860,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'United Republic of Tanzania','region': 'Africa','total': 509,'new': 0,'deaths': 21,'transmission classification': 'Pending'})
        writer.writerow({'country': 'United States of America','region': 'Americas','total': 33072912,'new': 16551,'deaths': 592932,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'United States Virgin Islands','region': 'Americas','total': 3618,'new': 10,'deaths': 28,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Uruguay','region': 'Americas','total': 322978,'new': 4195,'deaths': 4749,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Uzbekistan','region': 'Europe','total': 102605,'new': 243,'deaths': 702,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Vanuatu','region': 'Western Pacific','total': 3,'new': 0,'deaths': 0,'transmission classification': 'No Active Vases'})
        writer.writerow({'country': 'Venezuela','region': 'Americas','total': 245300,'new': 1679,'deaths': 2750,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Vietnam','region': 'Western Pacific','total': 9635,'new': 413,'deaths': 55,'transmission classification': 'Cluster of Cases'})
        writer.writerow({'country': 'Wallis and Futuna','region': 'Western Pacific','total': 454,'new': 0,'deaths': 7,'transmission classification': 'Sporadic Cases'})
        writer.writerow({'country': 'Yemen','region': 'Eastern Mediterranean','total': 6832,'new': 9,'deaths': 1337,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Zambia','region': 'Africa','total': 103763,'new': 1767,'deaths': 1324,'transmission classification': 'Community Transmission'})
        writer.writerow({'country': 'Zimbabwe','region': 'Africa','total': 39432,'new': 111,'deaths': 1622,'transmission classification': 'Community Transmission'})
        #writer.writerow({'country': '','total': ,'new': ,'deaths': }) #for reference--

if __name__ == "__main__":
    main()
